---
baseURL: https://swiftycode.com/
title: Swifty Code
paginate: 10
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: 
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Swifty Code
  description: "Weekly coding updates to empower your Swift skills by Alireza Rezagholian
    \U0001F680"
  keywords:
  - Blog
  - Portfolio
  - PaperMod
  author: Me
  images:
  - "<link or path of image for opengraph, twitter-cards>"
  DateFormat: January 2, 2006
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: "/favicon-16.png"
    favicon16x16: "/favicon-16.png"
    favicon32x32: "/favocon-32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/apple-touch-icon.png"
  label:
    text: Home
    icon: "/apple-touch-icon.png"
    iconHeight: 35
  profileMode:
    enabled: false
    title: Swifty Code
    subtitle: "Weekly coding updates to empower your Swift skills by Alireza Rezagholian
      \U0001F680"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags
  homeInfoParams:
    Title: Swifty Code âœ¨
    Content: "Weekly coding updates to empower your Swift skills by Alireza Rezagholian
      \U0001F680"
  socialIcons:
  - name: twitter
    url: https://twitter.com/swiftycode_com
  - name: linkedin
    url: https://linkedin.com/in/alireza1
  - name: github
    url: https://github.com/swiftycode-com
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: https://github.com/<path_to_repo>/content
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
    - title
    - permalink
    - summary
    - content
menu:
  main:
  - url: "/topics"
    name: Topics
    weight: 1
